'use client';

import { useState, type FormEvent, type ReactNode } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { questionCategories } from '@/lib/question-bank';

type Task = { id: string; title: string; description: string; category: string; priority: string; status: 'NOT_STARTED'|'IN_PROGRESS'|'COMPLETED'|'SKIPPED'; scheduledDate: string; estimatedMinutes: number; relatedQuestion: { id: string }|null };
type Plan = { id: string; title: string; targetRole: string; targetCompany: string|null; experienceLevel: string; durationDays: number; overview: string; focusAreas: string[]; technicalTopics: string[]; behavioralTopics: string[]; resumeTopics: string[]; tasks: Task[] };
type Props = { initialPlans: Plan[]; resumes: {id:string;fileName:string}[]; defaults?: {targetRole?:string|null;experienceLevel?:string|null;preferredAIProvider?:string|null} };

export function PreparationClient({ initialPlans, resumes, defaults }: Props) {
  const router = useRouter(); const [plans, setPlans] = useState(initialPlans); const [plan] = plans;
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [view, setView] = useState<'list'|'timeline'>('list'); const [showForm, setShowForm] = useState(!plan); const [regenerate, setRegenerate] = useState(false);
  const [form, setForm] = useState({ targetRole: defaults?.targetRole || '', targetCompany: '', experienceLevel: defaults?.experienceLevel || 'Fresher', jobDescription: '', resumeId: '', durationDays: '14', aiModel: defaults?.preferredAIProvider || 'ChatGPT' });
  const [manual, setManual] = useState(false);
  const completed = plan?.tasks.filter((task) => task.status === 'COMPLETED').length || 0; const total = plan?.tasks.length || 0; const percent = total ? Math.round(completed * 100 / total) : 0;
  const today = new Date(); const todayTasks = plan?.tasks.filter((task) => new Date(task.scheduledDate).toDateString() === today.toDateString()) || [];
  const nextTask = plan?.tasks.find((task) => task.status === 'NOT_STARTED' || task.status === 'IN_PROGRESS');
  const groups = (plan?.tasks || []).reduce<Record<string, Task[]>>((all, task) => { const key = new Date(task.scheduledDate).toDateString(); (all[key] ||= []).push(task); return all; }, {});

  async function createPlan(event: FormEvent) {
    event.preventDefault(); setBusy(true); setError('');
    try { const response = await fetch('/api/preparation', { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({...form, durationDays:Number(form.durationDays), ...(regenerate && plan ? {regeneratePlanId:plan.id} : {})}) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Unable to create plan.'); setPlans((items)=>regenerate?items.map((item)=>item.id===result.plan.id?result.plan:item):[result.plan,...items]); setShowForm(false); setRegenerate(false); setNotice(result.notice || 'Plan created. AI recommendations are suggestions, not guarantees.'); router.refresh(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to create plan.'); } finally { setBusy(false); }
  }
  async function updateStatus(task: Task, status: Task['status']) {
    setError(''); const response = await fetch('/api/preparation/tasks', { method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:task.id,status}) }); const result=await response.json(); if(!response.ok){setError(result.error||'Unable to update task.');return;} setPlans((items)=>items.map((item)=>item.id===plan?.id?{...item,tasks:item.tasks.map((entry)=>entry.id===task.id?{...entry,status}:entry)}:item));
  }
  async function addTask(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if(!plan)return; const data=new FormData(event.currentTarget); setBusy(true);
    try { const response=await fetch('/api/preparation/tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({planId:plan.id,title:data.get('title'),description:data.get('description'),category:data.get('category'),priority:data.get('priority'),date:new Date(String(data.get('date')||new Date().toISOString().slice(0,10))+'T12:00:00.000Z').toISOString()})}); const result=await response.json(); if(!response.ok)throw new Error(result.error); setPlans((items)=>items.map((item)=>item.id===plan.id?{...item,tasks:[...item.tasks,result.task]}:item)); setManual(false); }
    catch(cause){setError(cause instanceof Error?cause.message:'Unable to add task.');} finally{setBusy(false);}
  }

  return <main className="mx-auto max-w-7xl space-y-6">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm uppercase tracking-[0.22em] text-violet-300">Your practice workspace</p><h1 className="mt-2 text-3xl font-bold text-white">Interview Preparation</h1><p className="mt-2 text-slate-300">Build a focused practice plan for your target role.</p></div>{plan&&!showForm&&<div className="flex gap-2"><button className="btn-secondary" onClick={()=>{setRegenerate(true);setForm({...form,targetRole:plan.targetRole,targetCompany:plan.targetCompany||'',experienceLevel:plan.experienceLevel,durationDays:String(plan.durationDays)});setShowForm(true);}}>Regenerate Plan</button><button className="btn-primary" onClick={()=>{setRegenerate(false);setShowForm(true);}}>Create Preparation Plan</button></div>}</header>
    {error&&<p role="alert" className="rounded-lg border border-rose-500/40 bg-rose-500/10 p-3 text-sm text-rose-200">{error}</p>}{notice&&<p role="status" className="rounded-lg border border-violet-500/30 bg-violet-500/10 p-3 text-sm text-violet-100">{notice}</p>}
    {showForm&&<section className="card"><h2 className="text-xl font-semibold text-white">{regenerate?'Update Preparation Plan':'Create Preparation Plan'}</h2><p className="mt-2 text-sm text-slate-400">{regenerate?'Regeneration may use AI quota. Completed tasks stay saved; other recommendations are replaced.':'AI suggestions use only the context you choose and do not guarantee interview outcomes.'}</p><form className="mt-5 grid gap-4 md:grid-cols-2" onSubmit={createPlan}>
      <Field label="Target role"><input className="input" required maxLength={120} value={form.targetRole} onChange={e=>setForm({...form,targetRole:e.target.value})}/></Field><Field label="Target company (optional)"><input className="input" maxLength={120} value={form.targetCompany} onChange={e=>setForm({...form,targetCompany:e.target.value})}/></Field>
      <Field label="Experience level"><select className="input" value={form.experienceLevel} onChange={e=>setForm({...form,experienceLevel:e.target.value})}>{['Fresher','1-2 Years','3-5 Years','6-8 Years','8+ Years'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Preparation duration"><select className="input" value={form.durationDays} onChange={e=>setForm({...form,durationDays:e.target.value})}>{[['7 Days','7'],['14 Days','14'],['30 Days','30'],['Custom (up to 30 days)','21']].map(([x,y])=><option key={y} value={y}>{x}</option>)}</select></Field>
      <Field label="Resume (optional)"><select className="input" value={form.resumeId} onChange={e=>setForm({...form,resumeId:e.target.value})}><option value="">No resume</option>{resumes.map(x=><option key={x.id} value={x.id}>{x.fileName}</option>)}</select></Field><Field label="AI provider"><select className="input" value={form.aiModel} onChange={e=>setForm({...form,aiModel:e.target.value})}><option>ChatGPT</option><option>Gemini</option></select></Field>
      <div className="md:col-span-2"><label className="label" htmlFor="jd">Job description (optional)</label><textarea id="jd" className="input min-h-32" maxLength={10000} value={form.jobDescription} onChange={e=>setForm({...form,jobDescription:e.target.value})}/></div>
      <div className="flex gap-3 md:col-span-2"><button className="btn-primary" disabled={busy}>{busy?'Generating…':'Generate plan'}</button>{plan&&<button type="button" className="btn-secondary" onClick={()=>setShowForm(false)}>Cancel</button>}</div>
    </form></section>}
    {!plan&&!showForm&&<section className="card text-center"><h2 className="text-xl font-semibold text-white">Start with a focused plan</h2><p className="mt-2 text-slate-300">Create a plan for your target role and organize what to practice next.</p><button className="btn-primary mt-5" onClick={()=>setShowForm(true)}>Create Preparation Plan</button></section>}
    {plan&&<>
      <section className="grid gap-4 lg:grid-cols-3"><div className="card lg:col-span-2"><p className="text-sm text-violet-300">CURRENT PLAN</p><h2 className="mt-2 text-2xl font-semibold text-white">{plan.targetRole}{plan.targetCompany?` · ${plan.targetCompany}`:''}</h2><p className="mt-1 text-sm text-slate-400">{plan.experienceLevel} · {plan.durationDays} day preparation period</p><p className="mt-4 text-sm leading-6 text-slate-300">{plan.overview}</p><div className="mt-5 flex items-center justify-between text-sm"><span className="font-medium text-white">Preparation Progress</span><span>{completed} of {total} tasks completed · {percent}%</span></div><div className="mt-2 h-2 rounded-full bg-slate-700" role="progressbar" aria-label="Preparation progress" aria-valuenow={percent} aria-valuemin={0} aria-valuemax={100}><div className="h-2 rounded-full bg-violet-500" style={{width:`${percent}%`}}/></div></div><div className="card"><h2 className="text-lg font-semibold text-white">Today&apos;s Preparation</h2>{todayTasks.length?<p className="mt-3 text-sm text-slate-300">{todayTasks.filter(t=>t.status==='COMPLETED').length} of {todayTasks.length} tasks complete</p>:<p className="mt-3 text-sm text-slate-300">You&apos;re all caught up.</p>}{nextTask&&<div className="mt-4 rounded-lg border border-slate-700 p-3"><p className="text-xs text-violet-300">NEXT RECOMMENDED</p><p className="mt-1 font-medium text-white">{nextTask.title}</p><button className="btn-secondary mt-3" onClick={()=>updateStatus(nextTask,nextTask.status==='IN_PROGRESS'?'COMPLETED':'IN_PROGRESS')}>{nextTask.status==='IN_PROGRESS'?'Complete':'Start'}</button></div>}</div></section>
      <div className="grid gap-6 lg:grid-cols-[0.8fr_1.2fr]"><section className="card"><h2 className="text-xl font-semibold text-white">Recommended Focus Areas</h2>{plan.focusAreas.length?<ul className="mt-4 space-y-2">{plan.focusAreas.map(x=><li key={x} className="rounded-lg border border-slate-700 px-3 py-2 text-sm text-slate-200">{x}</li>)}</ul>:<p className="mt-3 text-sm text-slate-400">Complete a practice session to receive personalized recommendations.</p>}<div className="mt-5 grid gap-4 sm:grid-cols-2"><Topic title="Technical Topics" items={plan.technicalTopics}/><Topic title="Behavioral Topics" items={plan.behavioralTopics}/><Topic title="Resume Topics" items={plan.resumeTopics}/></div><Link className="btn-secondary mt-5 inline-flex" href={`/question-bank?jobRole=${encodeURIComponent(plan.targetRole)}`}>Browse recommended questions</Link></section>
      <section className="card"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-semibold text-white">Daily Practice Tasks</h2><div className="flex gap-2"><button className="btn-secondary" aria-pressed={view==='list'} onClick={()=>setView('list')}>List view</button><button className="btn-secondary" aria-pressed={view==='timeline'} onClick={()=>setView('timeline')}>Timeline</button><button className="btn-secondary" onClick={()=>setManual(!manual)}>Add task</button></div></div>
       {manual&&<form onSubmit={addTask} className="mt-4 grid gap-3 rounded-lg border border-slate-700 p-4 sm:grid-cols-2"><Field label="Task name"><input className="input" name="title" required maxLength={140}/></Field><Field label="Category"><select className="input" name="category">{questionCategories.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Priority"><select className="input" name="priority"><option>MEDIUM</option><option>HIGH</option><option>LOW</option></select></Field><Field label="Date"><input className="input" type="date" name="date" defaultValue={new Date().toISOString().slice(0,10)}/></Field><div className="sm:col-span-2"><label className="label">Description</label><textarea className="input" name="description" maxLength={500}/></div><button className="btn-primary" disabled={busy}>Save task</button></form>}
       <div className="mt-4 space-y-3">{view==='timeline'?Object.entries(groups).map(([date,items])=><div key={date} className="border-l-2 border-violet-500/50 pl-4"><h3 className="font-semibold text-violet-200">{new Date(date).toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'})}</h3>{(items||[]).map(task=><TaskCard key={task.id} task={task} update={updateStatus}/>)}</div>):plan.tasks.map(task=><TaskCard key={task.id} task={task} update={updateStatus}/>)}</div>
      </section></div>
    </>}
  </main>;
}
function Field({label,children}:{label:string;children:ReactNode}){return <div><label className="label">{label}</label>{children}</div>}
function Topic({title,items}:{title:string;items:string[]}){return <div><h3 className="text-sm font-medium text-white">{title}</h3><p className="mt-1 text-sm text-slate-400">{items.length?items.join(', '):'No recommendations yet.'}</p></div>}
function TaskCard({task,update}:{task:Task;update:(task:Task,status:Task['status'])=>void}){const next=task.status==='NOT_STARTED'?'IN_PROGRESS':task.status==='IN_PROGRESS'?'COMPLETED':'NOT_STARTED';return <article className="mt-2 rounded-lg border border-slate-700 bg-slate-950/40 p-3"><div className="flex flex-wrap items-start justify-between gap-3"><div><h4 className="font-medium text-white">{task.title}</h4><p className="mt-1 text-sm text-slate-400">{task.description}</p><p className="mt-2 text-xs text-slate-400">{task.category} · {task.priority} priority · {task.estimatedMinutes} min · {new Date(task.scheduledDate).toLocaleDateString()}</p><p className="mt-1 text-xs text-slate-300">Status: {task.status.replace('_',' ')}</p></div><div className="flex flex-wrap gap-2"><button className="btn-secondary" onClick={()=>update(task,next)}>{task.status==='NOT_STARTED'?'Start':task.status==='IN_PROGRESS'?'Complete':'Resume'}</button>{task.status!=='COMPLETED'&&task.status!=='SKIPPED'&&<button className="btn-secondary" onClick={()=>update(task,'SKIPPED')}>Skip</button>}<Link className="btn-secondary" href={`/question-bank?category=${encodeURIComponent(task.category)}`}>Practice this</Link><Link className="btn-secondary" href="/interviews/create">Start session</Link></div></div></article>}
