import { getServerSession } from 'next-auth';
import { NextResponse } from 'next/server';
import { z } from 'zod';
import { authOptions } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import { enforceSimulatorDailyLimit } from '@/lib/billing/feature-access';

const schema=z.object({targetRole:z.string().trim().min(1).max(120),company:z.string().trim().max(120).optional().default(''),experience:z.enum(['Fresher','1-2 Years','3-5 Years','6-8 Years','8+ Years']),resumeId:z.string().cuid().nullable().optional(),jobDescription:z.string().max(10000).optional().default(''),interviewType:z.enum(['HR','Behavioral','Technical','Managerial','Mixed','System Design','Project / Resume Based']),questionLimit:z.union([z.literal(5),z.literal(10),z.literal(15),z.literal(20)]),difficulty:z.enum(['Beginner','Intermediate','Advanced','Expert']),language:z.enum(['English','Hindi','Telugu','Tamil','Kannada','Malayalam','Marathi','Bengali']),aiModel:z.enum(['ChatGPT','Gemini']).default('ChatGPT')});
export async function GET(){const auth=await getServerSession(authOptions);if(!auth?.user?.id)return NextResponse.json({error:'Please sign in.'},{status:401});const sessions=await prisma.interviewSession.findMany({where:{userId:auth.user.id,isSimulator:true},select:{id:true,jobTitle:true,company:true,experience:true,simulatorInterviewType:true,simulatorDifficulty:true,simulatorQuestionLimit:true,status:true,simulatorFeedback:true,createdAt:true,_count:{select:{answers:true}}},orderBy:{createdAt:'desc'},take:30});return NextResponse.json({sessions:sessions.map(({_count,...s})=>({...s,answeredCount:_count.answers,createdAt:s.createdAt.toISOString()}))});}
export async function POST(request:Request){const auth=await getServerSession(authOptions);if(!auth?.user?.id)return NextResponse.json({error:'Please sign in to start a mock interview.'},{status:401});let body:unknown;try{body=await request.json();}catch{return NextResponse.json({error:'Invalid request body.'},{status:400});}const parsed=schema.safeParse(body);if(!parsed.success)return NextResponse.json({error:parsed.error.issues[0]?.message||'Check the simulator settings.'},{status:400});const d=parsed.data;try{await enforceSimulatorDailyLimit(auth.user.id);if(d.resumeId){const resume=await prisma.resume.findFirst({where:{id:d.resumeId,userId:auth.user.id,processingStatus:'COMPLETED'},select:{id:true}});if(!resume)return NextResponse.json({error:'Selected resume is unavailable.'},{status:400});}const created=await prisma.interviewSession.create({data:{userId:auth.user.id,company:d.company||'No company selected',jobTitle:d.targetRole,experience:d.experience,resumeId:d.resumeId||null,jobDescription:d.jobDescription||null,language:d.language,answerLength:'Balanced',answerFormat:'Normal',tone:'Professional',aiModel:d.aiModel,technicalDepth:'STANDARD',status:'DRAFT',isSimulator:true,simulatorInterviewType:d.interviewType,simulatorDifficulty:d.difficulty,simulatorQuestionLimit:d.questionLimit,simulatorState:{asked:0,skipped:0,startedAt:null,currentQuestion:null,coveredTopics:{}}}});return NextResponse.json({id:created.id},{status:201});}catch(error){const message=error instanceof Error?error.message:'Unable to create mock interview.';return NextResponse.json({error:message},{status:message.includes('limit')?429:500});}}
